name:                lambda-calculus-presentation
version:             0.1.0.0
github:              "supersven/lambda-calculus-presentation"
author:              "Sven Tennie"
maintainer:          "sven.tennie@gmail.com"
copyright:           "2018 - Sven Tennie"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/supersven/lambda-calculus-presentation#readme>

dependencies:
- base >= 4.7 && < 5

library:
    source-dirs: src
    dependencies:
      - containers >= 0.5.10.2
      - extra >= 1.6.9
    exposed-modules:
      - TypedCheck
      - UntypedEval
      - NaiveUntypedEval
      - UntypedSyntax
      - TypedSyntax
      
tests:
  lambda-calculus-presentation-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - lambda-calculus-presentation
      - hspec >= 2.4.8
      - containers >= 0.5.10.2
